package currencyRatesProvider.model;

public enum CurrencyCode {

//    UAH("Hryvnia"),
//    CAD("Canadian Dollar"),
//    CNY("Yuan Renminbi"),
//    CZK("Czech Koruna"),
//    DKK("Danish Krone"),
//    HUF("Forint"),
//    ILS("New Israeli Sheqel"),
//    JPY("Yen"),
//    KZT("Tenge"),
//    MDL("Moldovan Leu"),
//    NOK("Norwegian Krone"),
//    SGD("Singapore Dollar"),
//    SEK("Swedish Krona"),
//    CHF("Swiss Franc"),
//    RUB("Russian Ruble"),
//    GBP("Pound Sterling"),
//    USD("US Dollar"),
//    UZS("Uzbekistan Sum"),
//    BYN("Belarusian Ruble"),
//    TMT("Turkmenistan New Manat"),
//    AZN("Azerbaijanian Manat"),
//    TRY("Turkish Lira"),
//    EUR("Euro"),
//    PLZ("Zloty");

    UAH,
    CAD,
    CNY,
    CZK,
    DKK,
    HUF,
    ILS,
    JPY,
    KZT,
    MDL,
    NOK,
    SGD,
    SEK,
    CHF,
    RUB,
    GBP,
    USD,
    UZS,
    BYN,
    TMT,
    AZN,
    TRY,
    EUR,
    PLZ
}
